#!/bin/bash
mkdir /tmp/g || echo "Please remove the contents of /tmp/g" && exit
cd /tmp/g
#GCL
git clone https://github.com/czipperz/gcl
cd gcl
./install
cd ..

returnText=$(cat $HOME/.config/gcl)
if [ ! $returnText == "https://github.com/" ]; then
	echo "https://github.com/" > $HOME/.config/gcl
fi

#GD
gcl czipperz/gd
cd gd
./install
cd ..

#GC
gcl czipperz/gc
cd gc
./install
cd ..

#GR
gcl czipperz/gr
cd gr
./install
cd ..

echo "$returnText" > $HOME/.config/gcl
