#!/bin/bash
if [ -d /tmp/g ]; then
	echo "Please remove the contents of /tmp/g"
	exit 1
else
	mkdir /tmp/g
fi
cd /tmp/g

#GCL
git clone https://github.com/czipperz/gcl /tmp/g/gcl
cd /tmp/g/gcl
./install
cd /tmp/g

returnText=$(cat $HOME/.config/gcl)
[ $returnText == "https://github.com/" ] || echo "https://github.com/" > $HOME/.config/gcl

#GD
gcl czipperz/gd /tmp/g/gd
cd /tmp/g/gd
./install
cd /tmp/g

#GC
gcl czipperz/gc /tmp/g/gc
cd /tmp/g/gc
./install
cd /tmp/g

#GR
gcl czipperz/gr /tmp/g/gr
cd /tmp/g/gr
./install
cd /tmp/g

echo "$returnText" > $HOME/.config/gcl
